public with sharing class QuestionWrapper {
    @AuraEnabled
    public String Topic;
    @AuraEnabled
    public String Question_text;
    @AuraEnabled
    public String Option_A;
    @AuraEnabled
    public String Option_B;
    @AuraEnabled
    public String Option_C;
    @AuraEnabled
    public String Option_D;
    @AuraEnabled
    public String Option_E;
    @AuraEnabled
    public String Correct_Answers;
}
